### ISSUE TITLE
如何修改箭头颜色？

### ISSUE THREAD

**Issue by LinDaiDai** [LinDaiDai/bpmn-chinese-document#1]
![image](https://user-images.githubusercontent.com/30402039/79329433-6494c400-7f4a-11ea-95b2-1d4de166315a.png)

**Comment by LinDaiDai** [comment]
可以参考：https://github.com/bpmn-io/bpmn-js-examples/tree/master/theming

**Comment by zhengpingzou** [comment]
这个是设置流程设计器主题色值

**Comment by LinDaiDai** [comment]
对于箭头颜色：
```javascript
__modeler__.get('editorActions').trigger('setColor', {fill: 'red', stroke: 'red'})
```

**Comment by shelleyHLX** [comment]
大神，怎么设置一个箭头的颜色，而不是都是一个颜色的？

**Comment by gzh18678327207** [comment]
> 怎么设置一个箭头的大颜色，而不是一个颜色的？

我是自己把生成的箭头删了，然后自己重新绘制的每一个连线的箭头

**Comment by LinDaiDai** [comment]
https://github.com/PL-FE/bpmn-doc/blob/main/doc/customConnectionColor.md
