### ISSUE TITLE
请问下用户任务节点默认图标怎么修改

### ISSUE THREAD

**Issue by JsonandSesson** [LinDaiDai/bpmn-chinese-document#15]
![image](https://user-images.githubusercontent.com/23428823/86872378-ca8a8500-c10e-11ea-836f-4d5ef45bde81.png)
大佬，请教下

**Comment by JsonandSesson** [comment]
![image](https://user-images.githubusercontent.com/23428823/86872671-6e743080-c10f-11ea-9feb-5578305120c9.png)
![image](https://user-images.githubusercontent.com/23428823/86872691-77650200-c10f-11ea-8e1d-959b43e2113d.png)
我修改自定义图片之后会把整个区域也换成图片了

**Comment by weixin1239** [comment]
同问？？？

**Comment by weixin1239** [comment]
需求是需要更换用户任务里面的人物头像图标，求解！！！

**Comment by namewangwei** [comment]
有解决方案了吗

**Comment by HilaryPeng** [comment]
https://forum.bpmn.io/t/changing-icon-in-a-service-task-shape/2907 可以看一下这个
