### ISSUE TITLE
【求助】[完全自定义ContextPad] 按教程写，但是并没有替换默认的 ContextPad

### ISSUE THREAD

**Issue by Cloud33** [LinDaiDai/bpmn-chinese-document#19]
[完全自定义ContextPad] 按教程写，但是并没有替换默认的 ContextPad
![image](https://user-images.githubusercontent.com/8787198/89973928-39ba4280-dc94-11ea-9d37-f3020cc1da58.png)

效果是：只在附加自己注册的，但并没有替换掉默认的

代码：
![image](https://user-images.githubusercontent.com/8787198/89973868-10011b80-dc94-11ea-949e-66144e0a56e2.png)

注册：
![image](https://user-images.githubusercontent.com/8787198/89973949-476fc800-dc94-11ea-8938-f36518bdd446.png)

有什么不对的地方吗？

**Comment by LinDaiDai** [comment]
对比一下引入的时候和教材中的有什么不同，应该是可以的。因为每个案例我都试过。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LinDaiDai/bpmn-chinese-document"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午12:07
收件人:&nbsp;"LinDaiDai/bpmn-chinese-document"<bpmn-chinese-document@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LinDaiDai/bpmn-chinese-document] 【求助】[完全自定义ContextPad] 按教程写，但是并没有替换默认的 ContextPad (#19)





 
[完全自定义ContextPad] 按教程写，但是并没有替换默认的 ContextPad
 
 
效果是：只在附加自己注册的，但并没有替换掉默认的
 
代码：
 
 
注册：
 
 
有什么不对的地方吗？

**Comment by Cloud33** [comment]
OK，我找到其它方式了，也可以实现这种效果

**Comment by LinDaiDai** [comment]
哈哈哈，好的，棒






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LinDaiDai/bpmn-chinese-document"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 上午10:06
收件人:&nbsp;"LinDaiDai/bpmn-chinese-document"<bpmn-chinese-document@noreply.github.com&gt;;
抄送:&nbsp;"疯人院里的疯言疯语"<244508795@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LinDaiDai/bpmn-chinese-document] 【求助】[完全自定义ContextPad] 按教程写，但是并没有替换默认的 ContextPad (#19)





 
OK，我找到其它方式了，也可以实现这种效果

**Comment by xuehuaangel** [comment]
不能有那个自定义的名字 必须原模原样的去写那个contextPadProvider作为引入的名字 ,在这块纠结了4个小时
