### ISSUE TITLE
如何修改bpmn前缀？

### ISSUE THREAD

**Issue by zhaojinxiong** [LinDaiDai/bpmn-chinese-document#2]
dc 和 omgdc  需要在初始化的 definitions 上面定义 作用域 标签才会出现变化
[图片](https://tcjxgloss.oss-cn-beijing.aliyuncs.com/fda8e858f68ba8b99ac37d5d974068c.png)

**Comment by LinDaiDai** [comment]
厉害厉害୧(๑•̀◡•́๑)૭
