### ISSUE TITLE
https://blog.ops-coffee.cn/bpmn 同样写了一系列的bpmn文章，能否给加到教程列表里呢

### ISSUE THREAD

**Issue by ops-coffee** [LinDaiDai/bpmn-chinese-document#20]
需要用到bpmn-js，使用过程给记录到了这里：[https://blog.ops-coffee.cn/bpmn](https://blog.ops-coffee.cn/bpmn)

希望能够帮助有需要的小伙伴，大佬能否给加到[https://github.com/LinDaiDai/bpmn-chinese-document/blob/master/directory.md](https://github.com/LinDaiDai/bpmn-chinese-document/blob/master/directory.md)这个目录里？感谢

文章正在更新中

**Comment by wangzl1163** [comment]
> 需要用到bpmn-js，使用过程给记录到了这里：https://blog.ops-coffee.cn/bpmn
> 
> 希望能够帮助有需要的小伙伴，大佬能否给加到https://github.com/LinDaiDai/bpmn-chinese-document/blob/master/directory.md这个目录里？感谢
> 
> 文章正在更新中

modeler高级链接不对

**Comment by LinDaiDai** [comment]
> 需要用到bpmn-js，使用过程给记录到了这里：https://blog.ops-coffee.cn/bpmn
> 
> 希望能够帮助有需要的小伙伴，大佬能否给加到https://github.com/LinDaiDai/bpmn-chinese-document/blob/master/directory.md这个目录里？感谢
> 
> 文章正在更新中

可以很强，感谢大佬赏脸，已加。[微笑]
