### ISSUE TITLE
部分文章的图片好像是损坏了

### ISSUE THREAD

**Issue by duansheli** [LinDaiDai/bpmn-chinese-document#21]
有的图片只显示 十分之一 
只能看到个 header 
不知道是不是图片坏了 
麻烦更新下
----
比如这小节  全网最详bpmn.js教材-编辑、删除节点篇.md
![image](https://user-images.githubusercontent.com/8579595/107107260-08998400-686b-11eb-91c6-a081503007e3.png)

不是一两个图片就不一一列出了 
具体哪些图片坏了，每篇文章点进去看下

----
## 推荐个截图方案 给图片加个边框
截图后，用 picpick 编辑下图片

### 左边是原图 右边是编辑后图片
编辑后的图片加了个边框
![image](https://user-images.githubusercontent.com/8579595/107107202-90cb5980-686a-11eb-9cc0-1ba5c2c9a09d.png)

### 操作步骤
![image](https://user-images.githubusercontent.com/8579595/107107214-b48e9f80-686a-11eb-8eb6-6c1039ed705e.png)
![image](https://user-images.githubusercontent.com/8579595/107107218-bd7f7100-686a-11eb-9b94-4f121a6bd045.png)

**Comment by LinDaiDai** [comment]
你好，掘金上也可以找到相应的文章哈
https://juejin.cn/user/360295513463912/posts
