### ISSUE TITLE
label置于节点下方问题

### ISSUE THREAD

**Issue by 11010cy** [LinDaiDai/bpmn-chinese-document#25]
如在[label标签自定义在元素下方](https://github.com/LinDaiDai/bpmn-chinese-document/blob/master/LinDaiDai/%E5%85%A8%E7%BD%91%E6%9C%80%E8%AF%A6bpmn.js%E6%95%99%E6%9D%90-%E8%87%AA%E5%AE%9A%E4%B9%89renderer%E7%AF%87.md#label%E6%A0%87%E7%AD%BE%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9C%A8%E5%85%83%E7%B4%A0%E4%B8%8B%E6%96%B9)中的讨论，发现了另外一种可行的方法。

经查源码，在 `./node_modules/bpmn-js/lib/import/BpmnImporter.js` 185行可知，
```
// line 185
//  (optional) LABEL
if (isLabelExternal(semantic) && semantic.name) {
    this.addLabel(semantic, element);
 }
```
而isLabelExternal定义在 `./node_modules/bpmn-js/lib/util/LabelUtil.js`
```
// 22 
// Returns true if the given semantic has an external label
// Params:
// semantic: BpmnElement
// Returns:
// Boolean - true if has label
export function isLabelExternal(semantic) {
  return is(semantic, 'bpmn:Event') ||
         is(semantic, 'bpmn:Gateway') ||
         is(semantic, 'bpmn:DataStoreReference') ||
         is(semantic, 'bpmn:DataObjectReference') ||
         is(semantic, 'bpmn:DataInput') ||
         is(semantic, 'bpmn:DataOutput') ||
         is(semantic, 'bpmn:SequenceFlow') ||
         is(semantic, 'bpmn:MessageFlow') ;
}
```
所以，event节点、gateway节点等标签在节点下方，而Task节点不是。

故，可以通过将我们的节点添加到isLabelExternal修改默认标签行为。

如果你有更好的办法，欢迎讨论。

**Comment by LinDaiDai** [comment]
不错不错，好像还可以参考一下这里：https://juejin.cn/post/6983940380085452813
