### ISSUE TITLE
部分api已被bpmn弃用, 但教程还未更新.

### ISSUE THREAD

**Issue by siaikin** [LinDaiDai/bpmn-chinese-document#28]
1. [编写AuthorityPropertiesProvider.js代码](https://juejin.cn/post/6844904047279865869#heading-9) 
  1. bpmn-js-properties-panel@1.0.0 已弃用 getTabs https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/CHANGELOG.md#100

**Comment by LinDaiDai** [comment]
你好，可以看一下README最下面推荐的一些其它博主的文章哈，那里会新很多。当然，你的这个 issue 也可以作为后续人的参考。
