### ISSUE TITLE
解决信号 signalRef  引用  为undefined  

### ISSUE THREAD

**Issue by zhaojinxiong** [LinDaiDai/bpmn-chinese-document#9]
signalEventDefinition signalRef="undefined"
let signalRef = this.bpmnModeler.get('moddle').create('bpmn:Signal', {
            id: 'theSignalsss',
            name: 'xxx',
})

 let singalEvent = this.bpmnModeler.get('moddle').create('bpmn:SignalEventDefinition', {
    signalRef: signalRef,
 })

 this.modeling.updateProperties(elemnet, {
    eventDefinitions: [singalEvent],
  })

**Comment by LinDaiDai** [comment]
厉害厉害୧(๑•̀◡•́๑)૭
